---
- name: Copy key
  copy: src=nginx_signing.key dest=/home/vagrant
- name: Add apt key
#  apt_key: keyserver=keyserver.ubuntu.com id=C300EE8C
  apt_key: data="{{ lookup('file', 'nginx_signing.key') }}" state=present
- name: Add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present
- name: Add deb-src repo
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx' state=present
- name: update cache
  apt: update_cache=yes
- name: Install nginx
  apt: name=nginx state=present
- name: Copy site config files 
  copy: src={{ item }} dest=/etc/nginx/sites-available
  with_items:
    - "{{ nginx_file }}"
